Sync `pkgx.dev` pantry

diff --git a/pantry/pkgx.dev/projects/gnu.org/gcc/package.yml b/pantry/pkgx.dev/projects/gnu.org/gcc/package.yml
--- a/pantry/pkgx.dev/projects/gnu.org/gcc/package.yml
+++ b/pantry/pkgx.dev/projects/gnu.org/gcc/package.yml
@@ -7,23 +7,23 @@ versions:
   strip: /^releases\/gcc-/
 
 dependencies:
-  gnu.org/binutils: '*' # linker needs `as`
-  gnu.org/gmp: '>=4.2'
-  gnu.org/mpfr: '>=2.4.0'
-  gnu.org/mpc: '>=0.8.0'
+  gnu.org/binutils: "*" # linker needs `as`
+  gnu.org/gmp: ">=4.2"
+  gnu.org/mpfr: ">=2.4.0"
+  gnu.org/mpc: ">=0.8.0"
   zlib.net: ^1.3
+  darwin/x86-64: # since 15.1.0
+    libisl.sourceforge.io: ^0
 
 build:
   dependencies:
     linux:
-      gnu.org/gcc: '*'
-    gnu.org/make: '*'
-    perl.org: '^5.6.1'
-    gnu.org/patch: '*'
-    curl.se: '*'
-    github.com/westes/flex: '*'
-    darwin/x86-64: # since 15.1.0
-      libisl.sourceforge.io: ^0
+      gnu.org/gcc: "*"
+    gnu.org/make: "*"
+    perl.org: "^5.6.1"
+    gnu.org/patch: "*"
+    curl.se: "*"
+    github.com/westes/flex: "*"
   working-directory: build
   script:
     # Applying ians patches on x86-64 too, since he sometimes gets fixes in faster, like:
@@ -176,13 +176,19 @@ test:
   - gcc --version | grep -q "pkgx GCC {{version}}"
   - gcc -print-libgcc-file-name
   - gcc -print-multiarch
-  # gha mac runners have broken SDKs...
+  # some gha mac runners have broken SDKs...
   - run:
-      - if ! test -f /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/AvailabilityInternalLegacy.h; then
+      - if ! test -f /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/AvailabilityInternalLegacy.h || ! test -f ; then
       - echo "Missing SDK; skipping remaining tests"
       - exit 0
       - fi
     if: darwin
+  - run:
+      - if test "{{hw.platform}}" = "darwin" && ! test -f /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_bounds.h || ! test -f ; then
+      - echo "Missing SDK; skipping remaining tests"
+      - exit 0
+      - fi
+    if: ">=15.2"
   - gcc -o test1 test.c -lgmp
   - ./test1
   - g++ -o test2 test.cc
